import { informationRows, placeLine } from "./facts";
import type { Copy } from "./types";

export const en: Copy = {
  nav: {
    home: "Introduction",
    event: "Championship",
    yogasana: "Yogasana",
    organisation: "People",
    prakriti: "Prakriti",
    story: "Four days",
    gallery: "Gallery",
    media: "Films",
    information: "About",
    menu: "Menu",
    close: "Close",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    skip: "Skip to content",
    skipIntro: "Skip intro",
  },
  footer: "7th State Yogasana Sports Championship 2026–27 · All Bengal Yogasana Sports Association · Yogasana Bharat, New Delhi · World Yogasana",
  lightbox: { previous: "Previous", next: "Next", close: "Close" },
  home: {
    presents: "Yogasana",
    title: "7th State Yogasana Sports Championship",
    bangla: "",
    championship: "2026–27",
    place: placeLine("en"),
    context: "The 7th State Yogasana Sports Championship, held at Bharat Sevashram Sangha in Muluk.",
    heroAlt: "Official banner for the 7th State Yogasana Sports Championship 2026–27 at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum.",
    leadEyebrow: "The championship",
    leadTitle: "A state championship, in an ashram.",
    leadEm: "",
    lead: "The 7th State Yogasana Sports Championship brought men and women to Bharat Sevashram Sangha, Muluk, Bolpur, from 1 to 4 October 2026. The All Bengal Yogasana Sports Association presented it.\n\nBefore the competition, there was a gathering. The four days tell what happened after that.",
    ctaProgramme: "Contents",
    ctaVisit: "The four days",
    programmeTitle: "The four days",
    programmeLead: "The opening is told first. The mornings on the grounds, and the close, follow it.",
    duringTitle: "During the championship",
    insideEyebrow: "Inside",
    insideTitle: "Inside the championship",
    insideLead: "Officials worked through papers on the verandah, athletes performed on the mat, and the proceedings were recorded from the hall floor. The gallery continues that account, moment by moment.",
    watchFilm: "Watch the film",
  },
  event: {
    eyebrow: "The championship",
    title: "The 7th State Yogasana Sports Championship.",
    present:
      "The All Bengal Yogasana Sports Association presents the championship at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum. The association is affiliated to Yogasana Bharat, New Delhi, and to World Yogasana.",
    championship:
      "This is the state championship of Yogasana for West Bengal. Athletes come through an organised competitive pathway. The gathering ran from 1 to 4 October 2026.",
    motto: "समत्वं योग उच्यते",
    mottoNote: "The line on the Yogasana Bharat seal.",
    whyEyebrow: "The place",
    whyTitle: "The hall and the grounds.",
    whyEm: "",
    why: "Competition and gathering take place in the hall. Practice also moves onto the grounds of the ashram.",
    recordEyebrow: "Colophon",
    recordTitle: "About the championship",
    dateNote: "",
    rows: informationRows("en"),
    whatTitle: "What the championship is",
    what: "This is West Bengal’s state meet of competitive Yogasana, the 7th State Yogasana Sports Championship, 2026–27. It ran from 1 to 4 October 2026 at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum, in the hall of Sri Sri Shiv Mandir and on the grounds around it.\n\nThe All Bengal Yogasana Sports Association presented it, affiliated to Yogasana Bharat, New Delhi, and to World Yogasana. Karmyog for the 21st Century and Bharatiya Krishak Samaj joined as organisers.",
    sportLink: "Yogasana, as a sport",
    whoTitle: "Athletes",
    who: "Men and women came through district competition into this state field, and stayed with it across the four days.",
    judgedTitle: "Competition",
    judged: "Artistic Yogasana was contested. What had been prepared on the mats was performed in the hall of Sri Sri Shiv Mandir. The dais and the long table faced that same room.",
    judgingTitle: "Judging",
    judging: "A judging panel assessed the performances. District judging had already shaped who reached this state meet.",
    gatheringTitle: "Around the competition",
    gathering: "Dance sat in the same hall as the sport. Beyond the hall, the championship used a verandah, a field, and a courtyard. Flag hosting belonged to those mornings.",
    whereTitle: "The four days",
    where: "1 October opened in the hall. 2 October gathered athletes on the verandah and the field, then onto the mats. 3 October began in the courtyard, with an address and a fire offering, then portraits, recording, and an indoor evening. 4 October closed on performance, judging, and recognition.",
    experienceTitle: "Recognition",
    experience: "Recognition in the hall was a medal placed, and a certificate held beside the athlete. Both belonged to the gathering that had held the competition.",
  },
  story: {
    eyebrow: "The grounds",
    title: "The gathering on the field.",
    em: "The gathering on the field.",
    hall: "",
    ground: "The morning programme includes flag hosting, a fire offering and Yogasana practice, before the competition.",
    courtyardTitle: "The offering.",
    courtyard: "A fire offering is held in the courtyard at Muluk.",
    arriveTitle: "A different kind of venue.",
    arrive: "The championship is held in the green grounds of Bharat Sevashram Sangha at Muluk. Young athletes gather along the mandir verandah, in a setting unlike a city sports ground.",
    addressTitle: "",
    address: "",
    danceTitle: "",
    dance: "",
    bannerTitle: "",
    banner: "",
    morningTitle: "Know the path you are entering.",
    morning: "Young athletes are asked to understand the competitive route they are entering, not only the event in front of them.",
    practiceTitle: "Practice, together.",
    practice: "Athletes practise together on the mats. The association team leads the session.",
    nightTitle: "",
    night: "",
    interview: "Later in the championship a conversation was recorded before the Prakriti Jagaran banner. It set the mat beside food, farming, and the lives that follow. The speaker is not identified in that frame.",
    interviewEyebrow: "A conversation",
    interviewTitle: "Beyond the mat.",
    interviewNote: "Recorded at the championship. Not a speech from the opening.",
    daysLabel: "The four days",
    daysLead: "From 1 to 4 October 2026 the championship occupied Bharat Sevashram Sangha at Muluk: the hall of Sri Sri Shiv Mandir, the courtyard, the field, and the rooms where athletes stayed.",
    platesEyebrow: "Plates",
    platesTitle: "The visual record",
    days: [
      {
        id: "day-01",
        number: "01",
        title: "The championship opens",
        opening: "On 1 October 2026 the championship opened at Bharat Sevashram Sangha in Muluk, Bolpur, Birbhum.",
        passages: [
          "The association had asked colleges and universities in West Bengal for a ground. None offered one. Bharat Sevashram Sangha took the meet in, through the interest of Swami Shanti Maharaj. The chair asked whoever led the association afterwards not to leave the Sangha.",
          "Sourav J. Sarkar was introduced as Mahacharya, and as State President of Bharatiya Krishak Samaj in West Bengal. The chair remarked that he was an IIT student, and spoke of science in the farming of the Gangetic plain.",
          "The chair said the state field was larger than the previous year’s championship, and that rooms and meals at the ashram were already stretched. He asked the district committees to send no more. Standing in Birbhum, he said an opening could not leave Rabindranath aside. He introduced Kalyan Mukhopadhyay, a retired IPS officer who had long handled the West Bengal police.",
          "A woman who had arranged district judging from home was thanked. She said the women with her were homemakers, learning the work as they were asked to do it. A Vedic invocation was then chanted in the hall.",
          "Swami Shanti Maharaj welcomed the districts. He noted that the lodging was imperfect, and recalled Swami Paramananda’s point that a seeker’s practice does not run on comfort. He returned the word yoga to yuj: to join, and to bring the mind under control.",
          "A rhythmic, artistic presentation followed in the hall.",
          "Kalyan Mukhopadhyay said a yogasana is complete only when the body, the mind, and one’s conduct are all held, and that the police needed that kind of control. Supriyo Mukherjee, asked to help the meet be seen, spoke of how media had lifted kabaddi from a village game, and said he would look at what might be done for competitive Yogasana.",
          "Someone introduced as Rina-ji said practice has to continue, whether or not anyone wins. Major Saheb asked that yoga be of the mind as well as the body. He recalled Rabindranath’s image of keeping company with the world, and left one line in English: “I for Illness, We for Wellness.” The thanks then turned to Papiya Bhattacharya (Roy), General Secretary.",
        ],
        close: "From that opening, the championship moved into its working days.",
      },
      {
        id: "day-02",
        number: "02",
        title: "The championship enters its rhythm",
        opening: "On 2 October the morning opened along the verandah of Sri Sri Shiv Mandir.",
        passages: [
          "Young athletes took their places along the mandir verandah at Muluk. Cameras were already set. The day had not yet become the mats.",
          "The group then sat in a circle on the field. Separate arrivals became one body, still inside the championship that had opened the day before. The association team was among them.",
          "Arms rose together. Beside the health centre, the association team led from the front of the mat: low postures, and repetition.",
        ],
        close: "Practice gave the second day its shape.",
      },
      {
        id: "day-03",
        number: "03",
        title: "The championship deepens",
        opening: "On 3 October the morning opened in the courtyard at Muluk.",
        passages: [
          "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, addressed the gathering seated on the mats. Athletes and officials were in the same courtyard, before the day moved into the hall.",
          "A fire offering followed in that courtyard. Shyamal Ta sat beside the fire, microphone in hand, with athletes and officials around him.",
          "The day then turned to portraits before the championship banner, and to the hall being filmed. By evening, young athletes sat together indoors, officials behind them.",
        ],
        close: "By evening, the gathering had moved from the open courtyard into the hall.",
      },
      {
        id: "day-04",
        number: "04",
        title: "The four days close",
        opening: "On 4 October the championship closed at the same ashram.",
        passages: [
          "The last day was performance in the hall of Sri Sri Shiv Mandir, before the judging panel.",
          "A medal was placed. A certificate was held beside the athlete.",
          "Athletes had stayed and eaten at the Sangha across the four days. The championship closed on that shared time, and on the recognition in the hall.",
        ],
        close: "The championship closed on the four days at Muluk.",
      },
    ],
  },
  gallery: {
    eyebrow: "Photographs",
    title: "Photographs from the championship",
    em: "Individual moments from the championship. The four days explain what they belonged to.",
    groups: [
      { id: "day-01", kicker: "1 October 2026", title: "The championship opens", note: "1 October opened the championship at Bharat Sevashram Sangha in Muluk. The hall was Sri Sri Shiv Mandir." },
      { id: "day-02", kicker: "2 October 2026", title: "Gathering into practice", note: "2 October gathered athletes on the verandah and the field, then onto the mats beside the health centre." },
      { id: "day-03", kicker: "3 October 2026", title: "From the courtyard to the hall", note: "3 October opened in the courtyard with an address and a fire offering, then moved to portraits, recording, and an indoor evening session." },
      { id: "day-04", kicker: "4 October 2026", title: "The four days close", note: "4 October was the last day. Certificates, medals, and the shared stay close the four-day record." },
      { id: "wider", kicker: "The wider record", title: "Hall and recognition", note: "Addresses from the long table, the presentation of certificates and medals, and the evening session in the hall." },
    ],
  },
  media: {
    eyebrow: "Films",
    title: "Four films from the championship.",
    em: "Four films: the gathering, the hall of Sri Sri Shiv Mandir, the dais, and the long table.",
    play: "Play",
    fig: "Fig.",
  },
  information: {
    eyebrow: "Affiliation",
    title: "Event information",
    lead: "",
    affiliation:
      "Yogasana Bharat, New Delhi, is the national affiliation of the All Bengal Yogasana Sports Association.",
    organisersEyebrow: "Joint organisers",
    organisersTitle: "Joint organisers",
    organisers:
      "Karmyog for the 21st Century and Bharatiya Krishak Samaj are joint organisers of the championship.",
    closeEyebrow: "Close",
    closeTitle: "Prakriti Jagaran Mancha",
    closeName: "Prakriti Jagaran Mancha",
    closePlace: "Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum",
    closeDate: "",
  },
  yogasana: {
    eyebrow: "The sport",
    title: "From practice to performance.",
    em: "",
    lead: "From district competition to the state.",
    practice:
      "On the mat at Muluk, Yogasana was repetition, control, and precision. Beside the health centre, the association team led from the front. The postures prepared a performance. The performance itself waited for the hall.",
    sport:
      "Competitive Yogasana is that work performed in public. Artistic Yogasana was the form contested at this meet. The portrait before the championship banner records an athlete in the gathering, not a result.",
    mottoGloss: "Equanimity is Yoga",
    session: "Judged as a sport.",
    pathway:
      "District competition led into this state meet. A state result can lead on to the national level. That is the route the association describes.",
    mottoNote: "The line on the Yogasana Bharat seal.",
  },
  organisation: {
    eyebrow: "The association",
    title: "The association that held the championship.",
    lead: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association and an executive committee member of Yogasana Bharat, held the offices that ran the championship. Papiya Bhattacharya (Roy) was General Secretary. The association carried selection, judging, accommodation, and the route from district competition toward higher Yogasana.",
    filmedTitle: "Documenting the proceedings.",
    filmed:
      "The association’s work is visible around the athletes: officials gathered in the courtyard, and the hall filmed while the programme is underway.\n\nThe championship was documented alongside the sporting programme, so conversations and proceedings were kept with the competition on the mat.",
    leadersEyebrow: "Event leadership",
    presidentTerm: "State President",
    president: "Shyamal Ta",
    secretaryTerm: "General Secretary",
    secretary: "Papiya Bhattacharya (Roy)",
    joint:
      "Young athletes need a clear view of the competitive route they are entering, so that practice and competition can lead toward higher-level Yogasana.",
    partnersTitle: "Partners",
    abysaRole: "Presents and runs the state championship: selection, judging, accommodation, and preparation for higher-level competition.",
    nationalRole: "National affiliation of the All Bengal Yogasana Sports Association.",
    worldRole: "The World Yogasana mark is carried on the championship banner with Yogasana Bharat.",
    jointRole: "Joint organisers.",
    eventLeadership: "Event leadership",
    eventLeadershipTitle: "All Bengal Yogasana Sports Association",
    institutionalLeadership: "Institutional leadership",
    institutionalLeadershipTitle: "Yogasana Bharat and World Yogasana",
    institutionalNote: "Udit Seth and Jaideep Arya are named on the official championship banner, with the national and world offices.",
    profiles: {
      "shyamal-ta": {
        name: "Shyamal Ta",
        role: "State President, All Bengal Yogasana Sports Association",
        detail: "Executive committee member, Yogasana Bharat",
        alt: "Portrait of Shyamal Ta, State President of the All Bengal Yogasana Sports Association, from the official championship banner.",
      },
      "papiya-bhattacharya-roy": {
        name: "Papiya Bhattacharya (Roy)",
        role: "General Secretary, All Bengal Yogasana Sports Association",
        detail: "",
        alt: "Portrait of Papiya Bhattacharya (Roy), General Secretary of the All Bengal Yogasana Sports Association, from the official championship banner.",
      },
      "udit-seth": {
        name: "Udit Seth",
        role: "President, Yogasana Bharat",
        detail: "",
        alt: "Portrait of Udit Seth, President of Yogasana Bharat, from the official championship banner.",
      },
      "jaideep-arya": {
        name: "Jaideep Arya",
        role: "General Secretary, World Yogasana and Yogasana Bharat",
        detail: "",
        alt: "Portrait of Jaideep Arya, General Secretary of World Yogasana and Yogasana Bharat, from the official championship banner.",
      },
    },
  },
  prakriti: {
    eyebrow: "Beyond the mat",
    title: "Yogasana, food, and the next generation.",
    bangla: "Prakriti Jagaran Mancha",
    lead: "Prakriti Jagaran Mancha is the name this championship used for a concern beside the sport: how people eat, how they farm, and what that leaves the young. The All Bengal Yogasana Sports Association presented the meet. This name marked a subject inside it.",
    note: "",
    definition: "",
    sections: [
      {
        title: "Health, food, agriculture",
        body: "At the opening, the chair spoke of science in the cultivation of the Gangetic plain. Bharatiya Krishak Samaj, a joint organiser, was the farmers’ organisation in that room.\n\nA conversation recorded later, before the Prakriti Jagaran banner, returned to the meal and to the next generation. The person speaking in that frame is not named.",
      },
      {
        title: "Why it was part of the championship",
        body: "Judging, certificates, and medals remained the sporting close. The wider subject was the company the meet kept: an ashram, a farmers’ organisation, and a sporting body, on the same grounds, while athletes performed.",
      },
    ],
  },
  captions: {
    "athletes-hall": {
      alt: "Young athletes in orange shirts seated on the floor of the hall, listening.",
      caption: "Athletes of the state championship, seated in the hall at Sri Sri Shiv Mandir.",
    },
    "hall-assembly": {
      alt: "A wide view of the hall at Sri Sri Shiv Mandir, with the gathering seated before the dais.",
      caption: "The hall at Sri Sri Shiv Mandir, Bharat Sevashram Sangha.",
    },
    "championship-dais": {
      alt: "The dais beneath the banner of the 7th State Yogasana Sports Championship 2026-27.",
      caption: "7th State Yogasana Sports Championship 2026–27, men and women.",
    },
    address: {
      alt: "A speaker in yellow stands at a microphone beside the long table.",
      caption: "An address from the table in the hall.",
    },
    "dais-speaker": {
      alt: "A speaker with a microphone stands among officials at the championship dais.",
      caption: "The dais, with the championship banner behind.",
    },
    "dance-pair": {
      alt: "Two dancers in red and cream perform in the hall while the audience watches.",
      caption: "Dance in the hall during the gathering.",
    },
    "dance-record": {
      alt: "Dancers mid-movement, with a phone held up to record the performance.",
      caption: "The dance in the hall, recorded from the floor.",
    },
    "dance-turn": {
      alt: "Dancers seen from behind, turning in red blouses and cream skirts.",
      caption: "Dancers turn in the hall.",
    },
    remembrance: {
      alt: "A woman in a yellow saree holds a framed portrait at the ceremonial table.",
      caption: "A framed portrait is brought to the long table during the championship gathering.",
    },
    "ceremony-table": {
      alt: "People gathered at a long table under the sign of Sri Sri Shiv Mandir.",
      caption: "The long table beneath the sign of Sri Sri Shiv Mandir.",
    },
    offering: {
      alt: "A woman in white walks toward the dais as the hall watches.",
      caption: "Approaching the dais in the hall.",
    },
    "young-athletes": {
      alt: "Rows of young athletes in orange sit along the mandir corridor.",
      caption: "Young athletes seated along the mandir corridor.",
    },
    "hall-wide": {
      alt: "The long hall opens onto the grounds, with children seated and cameras in the foreground.",
      caption: "The hall at Sri Sri Shiv Mandir, opening onto the grounds.",
    },
    "from-the-floor": {
      alt: "The gathering stands and sits around the dais, many holding phones.",
      caption: "The gathering around the dais, seen from the floor of the hall.",
    },
    "crossing-dais": {
      alt: "A blurred figure crosses in front of the championship dais.",
      caption: "Movement in front of the championship dais.",
    },
    "field-circle": {
      alt: "A circle seated on the ashram field at Muluk.",
      caption: "Athletes sit together on the field at Muluk.",
    },
    courtyard: {
      alt: "People seated on mats in the courtyard, facing an address.",
      caption: "People seated on mats in the courtyard.",
    },
    "practice-ground": {
      alt: "Practitioners hold a low posture on striped mats beside a small fire offering.",
      caption: "Morning yogasana practice on the mats beside the health centre at Muluk.",
    },
    "practice-warrior": {
      alt: "A wide lunge led on the forecourt, with the group practising on an orange mat.",
      caption: "A wide stance during morning practice on the forecourt.",
    },
    "practice-squat": {
      alt: "The group moves into a deep squat during morning practice.",
      caption: "A deep squat during morning practice on the mats.",
    },
    "practice-open": {
      alt: "Practitioners open the chest, arms extended, during the morning session.",
      caption: "Arms extended during morning practice on the mats.",
    },
    "practice-rise": {
      alt: "The group raises both arms, led by the All Bengal Yogasana Sports Association team.",
      caption: "Arms raised, led by the All Bengal Yogasana Sports Association team.",
    },
    "practice-lead": {
      alt: "An instructor seen from behind leads the group, incense smoke rising from the mats.",
      caption: "The association team leads morning practice at Muluk.",
    },
    "interview-seated": {
      alt: "A man is filmed in conversation before the Prakriti Jagaran banner.",
      caption: "A recorded conversation before the Prakriti Jagaran banner.",
    },
    "interview-camera": {
      alt: "A camera on a tripod set up before the event banner.",
      caption: "Recording equipment set up before the event banner.",
    },
    "film-corridor": {
      alt: "The gathering seated before the 7th State Yogasana Sports Championship banner and the Prakriti Jagaran banner.",
      caption: "The gathering seated before the championship banners.",
    },
    "film-athletes": {
      alt: "Athletes in orange seated in the hall at Sri Sri Shiv Mandir.",
      caption: "Athletes seated in the hall of Sri Sri Shiv Mandir.",
    },
    "film-dais": {
      alt: "The championship dais seen from within the seated gathering.",
      caption: "The championship dais, seen from within the gathering.",
    },
    "film-ceremony": {
      alt: "People gathered at the long table inside Sri Sri Shiv Mandir.",
      caption: "The long table during the championship gathering.",
    },
    "indoor-session": {
      alt: "Young athletes seated in rows during an indoor championship session, with officials behind them.",
      caption: "Young athletes seated together during an indoor session in the hall.",
    },
    "yt-verandah-table": {
      alt: "Officials seated at a long table on the verandah, writing on papers beside laptops.",
      caption: "Officials work through papers at a table on the verandah.",
    },
    "yt-standing-balance": {
      alt: "An athlete in a green, white and orange suit holds a standing balance, one foot drawn up behind the head.",
      caption: "An athlete holds a standing balance during a performance.",
    },
    "hall-crew": {
      alt: "A video camera on a tripod stands beside a sound desk and an open laptop on the hall floor.",
      caption: "Recording equipment set up on the hall floor during the championship.",
    },
    "recognition-stand": {
      alt: "An athlete in an orange shirt holds a medal while officials stand beside her in the hall.",
      caption: "An athlete receives a medal during recognition in the hall.",
    },
    "medal-placed": {
      alt: "A medal is placed over an athlete's head in the hall, while a certificate is held beside him.",
      caption: "A medal is placed as a certificate is held beside the athlete, during recognition in the hall.",
    },
    "certificate-youth": {
      alt: "A young athlete in orange holds a certificate in the hall.",
      caption: "An athlete holds a certificate presented in the hall.",
    },
    "portrait-blue": {
      alt: "An athlete waits with folded hands before the championship banner.",
      caption: "An athlete waits with folded hands before the championship banner.",
    },
    "portrait-yellow": {
      alt: "An athlete faces the camera in front of the championship banner, with a microphone clipped on.",
      caption: "An athlete faces the camera during recordings in front of the championship banner.",
    },
    "portrait-braid": {
      alt: "An athlete stands with folded hands and a microphone before the championship banner.",
      caption: "An athlete stands with folded hands while being recorded before the championship banner.",
    },
    "portrait-navy": {
      alt: "An athlete speaks into a microphone before the championship banner.",
      caption: "An athlete speaks into a microphone before the championship banner.",
    },
    "portrait-jersey": {
      alt: "An athlete is recorded before the championship banner on the morning of 3 October.",
      caption: "An athlete is recorded before the championship banner on the morning of 3 October.",
    },
    "interview-banner": {
      alt: "A man speaks in a recorded conversation before the Prakriti Jagaran banner.",
      caption: "A recorded conversation before the Prakriti Jagaran banner.",
    },
    "interview-sofa": {
      alt: "Two men sit for a filmed conversation in front of the championship banner.",
      caption: "A conversation recorded before the championship banner.",
    },
    "organisers-court": {
      alt: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, stands with officials and organisers in the courtyard at Bharat Sevashram Sangha, Muluk.",
      caption: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, with officials and organisers in the courtyard at Bharat Sevashram Sangha, Muluk.",
    },
  },
};
