import { informationRows, placeLine } from "./facts";
import type { Copy } from "./types";

export const en: Copy = {
  nav: {
    home: "Introduction",
    event: "Championship",
    yogasana: "Yogasana",
    organisation: "People",
    prakriti: "Prakriti",
    story: "Four days",
    gallery: "Gallery",
    media: "Films",
    information: "About",
    menu: "Menu",
    close: "Close",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    skip: "Skip to content",
    skipIntro: "Skip intro",
  },
  footer: "7th State Yogasana Sports Championship 2026–27 · All Bengal Yogasana Sports Association · Yogasana Bharat, New Delhi · World Yogasana",
  lightbox: { previous: "Previous", next: "Next", close: "Close" },
  home: {
    presents: "Yogasana",
    title: "7th State Yogasana Sports Championship",
    bangla: "",
    championship: "2026–27",
    place: placeLine("en"),
    context: "The 7th State Yogasana Sports Championship, held at Bharat Sevashram Sangha in Muluk.",
    leadEyebrow: "The championship",
    leadTitle: "Competitive Yogasana, over four days.",
    leadEm: "",
    lead: "From 1 to 4 October 2026, athletes from across West Bengal competed in Yogasana at Bharat Sevashram Sangha, Muluk, Bolpur. Practice, performance and judging shared the hall of Sri Sri Shiv Mandir and the grounds around it.\n\nThey had come through district competition into this state championship, on a pathway that continues beyond it. The All Bengal Yogasana Sports Association presented the four days. What follows is the record of how those days were lived.",
    ctaProgramme: "Contents",
    ctaVisit: "The four days",
    programmeTitle: "The four days",
    programmeLead: "The championship opened at the ashram. On 2 October athletes gathered along the verandah and on the field, then practised on the mats. On 3 October a courtyard address and a fire offering led into the hall. The last day closed on competition, judging, certificates, medals, and the shared stay.",
    duringTitle: "During the championship",
    insideEyebrow: "Inside",
    insideTitle: "Inside the championship",
    insideLead: "Officials worked through papers on the verandah, athletes performed on the mat, and the proceedings were recorded from the hall floor. The gallery continues that account, moment by moment.",
    watchFilm: "Watch the film",
  },
  event: {
    eyebrow: "The championship",
    title: "The 7th State Yogasana Sports Championship.",
    present:
      "The All Bengal Yogasana Sports Association presents the championship at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum. The association is affiliated to Yogasana Bharat, New Delhi, and to World Yogasana.",
    championship:
      "This is the state championship of Yogasana for West Bengal. Athletes come through an organised competitive pathway. The gathering ran from 1 to 4 October 2026.",
    motto: "समत्वं योग उच्यते",
    mottoNote: "The line on the Yogasana Bharat seal.",
    whyEyebrow: "The place",
    whyTitle: "The hall and the grounds.",
    whyEm: "",
    why: "Competition and gathering take place in the hall. Practice also moves onto the grounds of the ashram.",
    recordEyebrow: "Colophon",
    recordTitle: "About the championship",
    dateNote: "",
    rows: informationRows("en"),
    whatTitle: "What the championship is",
    what: "The 7th State Yogasana Sports Championship is West Bengal’s state meet of competitive Yogasana. It was held at Bharat Sevashram Sangha in Muluk, Bolpur, from 1 to 4 October 2026. Athletes practised, performed and were judged in the hall of Sri Sri Shiv Mandir and on the grounds around it.\n\nThe All Bengal Yogasana Sports Association presented the championship. It is affiliated to Yogasana Bharat, New Delhi, and to World Yogasana. Karmyog for the 21st Century and Bharatiya Krishak Samaj joined as organisers.",
    sportLink: "Yogasana, as a sport",
    whoTitle: "Who takes part",
    who: "Hundreds of athletes, men and women, competed. They arrived through district competition into this state championship.\n\nThe association holds that route in view: the competitions that brought athletes to Muluk, and the further competition a state result can open, including the national level. The ashram was one stage of that pathway, lived over four days.",
    judgedTitle: "How it is judged",
    judged: "A designated judging panel assessed each performance. What had been practised on the mats was performed and read for control, precision, and the discipline of a competitive asana.\n\nJudging sat with the competition in the hall. Practice on the grounds was where that performance was prepared. Addresses from the dais belonged to the same public room.",
    gatheringTitle: "Around the competition",
    gathering: "Sri Sri Shiv Mandir held more than the mats. Athletes gathered there for competition, addresses were made from the dais and the long table, and dance was part of the same assembly.\n\nThe hall opens onto the grounds. Morning gatherings at the ashram included flag hosting, a fire offering, and Yogasana practice. The courtyard, the field and the verandah carried the shared rhythm around the judged performance.",
    whereTitle: "Where it takes place",
    where: "The championship was held at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum. The hall is Sri Sri Shiv Mandir (শ্রী শ্রী শিব মন্দির). Competition used that hall and the grounds around it.\n\nThe courtyard and the field carried the morning gathering and the mats. The hall was the public room of the championship: competition, addresses, and dance.",
    experienceTitle: "What athletes experience",
    experience: "Across the four days, athletes stayed, practised and ate together. An evening session continued under the lights. Competition before the judging panel was the sporting centre of the event.\n\nIn the hall, athletes were recognised with certificates and medals. A medal was placed as a certificate was held beside the athlete. That recognition belonged to the same gathering that had held the competition.",
  },
  story: {
    eyebrow: "The grounds",
    title: "The gathering on the field.",
    em: "The gathering on the field.",
    hall: "",
    ground: "The morning programme includes flag hosting, a fire offering and Yogasana practice, before the competition.",
    courtyardTitle: "The offering.",
    courtyard: "A fire offering is held in the courtyard at Muluk.",
    arriveTitle: "A different kind of venue.",
    arrive: "The championship is held in the green grounds of Bharat Sevashram Sangha at Muluk. Young athletes gather along the mandir verandah, in a setting unlike a city sports ground.",
    addressTitle: "",
    address: "",
    danceTitle: "",
    dance: "",
    bannerTitle: "",
    banner: "",
    morningTitle: "Know the path you are entering.",
    morning: "Young athletes are asked to understand the competitive route they are entering, not only the event in front of them.",
    practiceTitle: "Practice, together.",
    practice: "Athletes practise together on the mats. The association team leads the session.",
    nightTitle: "",
    night: "",
    interview: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, speaks here about Yogasana together with healthier food, better farming, and the lives of the next generation.",
    interviewEyebrow: "A conversation",
    interviewTitle: "Beyond the mat.",
    interviewNote: "Shyamal Ta, State President",
    daysLabel: "The four days",
    daysLead: "From 1 to 4 October 2026 the championship occupied Bharat Sevashram Sangha at Muluk: the hall of Sri Sri Shiv Mandir, the courtyard, the field, and the rooms where athletes stayed.",
    platesEyebrow: "Plates",
    platesTitle: "The visual record",
    days: [
      {
        id: "day-01",
        number: "01",
        title: "The championship opens",
        opening: "On 1 October 2026 the championship opened at Bharat Sevashram Sangha in Muluk, Bolpur, Birbhum.",
        passages: [
          "Athletes who had already come through district competition arrived for the state gathering. Sri Sri Shiv Mandir was the hall that received them. Around it, the ashram held the rest of the championship: a verandah, a field, a courtyard, and the mats where practice would take shape.",
          "What they had entered was competitive Yogasana. The work of the four days would be practice, performance and judging, in a place that was also an ashram: flag hosting, a fire offering, and the shared stay sat beside the sport.",
          "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, led the championship, with Papiya Bhattacharya (Roy) as General Secretary. Men and women had come for the state gathering.",
        ],
        close: "From that opening, the championship moved into its working days.",
      },
      {
        id: "day-02",
        number: "02",
        title: "Gathering into practice",
        opening: "On 2 October the morning opened along the verandah of Sri Sri Shiv Mandir.",
        passages: [
          "Young athletes gathered along the mandir verandah at Bharat Sevashram Sangha, Muluk. The morning was an assembly, recorded as the athletes took their places, before the work on the mats.",
          "The group then moved onto the field and sat together in a circle. Separate arrivals became one body, still inside the championship that had opened the day before. The association team was among them.",
          "The rhythm turned to movement. Arms rose together, the association team leading from the front of the mat. Practice continued beside the health centre: low postures, repetition, the physical preparation that judging would later read as performance.",
        ],
        close: "Practice gave the second day its shape.",
      },
      {
        id: "day-03",
        number: "03",
        title: "From the courtyard to the hall",
        opening: "On 3 October the morning opened in the courtyard at Muluk.",
        passages: [
          "A speaker addressed the gathering seated on the mats. The address belonged to the working morning of the championship: athletes and officials together, before the day moved into the hall.",
          "A fire offering followed in the same courtyard. Athletes and officials sat around a small fire, hands folded. The offering stayed with the morning address, before the day turned to portraits, recording, and the indoor session.",
          "Athletes stood for portraits before the championship banner, and the hall was filmed. By evening, young athletes sat together indoors, with officials behind them.",
        ],
        close: "By evening, the gathering had moved from the open courtyard into the hall.",
      },
      {
        id: "day-04",
        number: "04",
        title: "The four days close",
        opening: "On 4 October the championship closed at the same ashram.",
        passages: [
          "The last day held what the four days had been building: practice on the mats, competition before a judging panel, and the hall of Sri Sri Shiv Mandir as the public room of the event.",
          "In that hall, athletes were recognised with certificates and medals. A medal was placed as a certificate was held beside the athlete. Recognition sat inside the gathering that had held the competition.",
          "Athletes had stayed at Bharat Sevashram Sangha, eaten together, and shared the grounds. Accommodation, meals and athlete facilities were part of those four days. The championship closed on that shared time.",
        ],
        close: "The championship closed on the four days at Muluk.",
      },
    ],
  },
  gallery: {
    eyebrow: "Photographs",
    title: "Photographs from the championship",
    em: "Individual moments from the championship. The four days explain what they belonged to.",
    groups: [
      { id: "day-01", kicker: "1 October 2026", title: "The championship opens", note: "1 October opened the championship at Bharat Sevashram Sangha in Muluk. The hall was Sri Sri Shiv Mandir." },
      { id: "day-02", kicker: "2 October 2026", title: "Gathering into practice", note: "2 October gathered athletes on the verandah and the field, then onto the mats beside the health centre." },
      { id: "day-03", kicker: "3 October 2026", title: "From the courtyard to the hall", note: "3 October opened in the courtyard with an address and a fire offering, then moved to portraits, recording, and an indoor evening session." },
      { id: "day-04", kicker: "4 October 2026", title: "The four days close", note: "4 October was the last day. Certificates, medals, and the shared stay close the four-day record." },
      { id: "wider", kicker: "The wider record", title: "Hall and recognition", note: "Addresses from the long table, the presentation of certificates and medals, and the evening session in the hall." },
    ],
  },
  media: {
    eyebrow: "Films",
    title: "Four films from the championship.",
    em: "Four films: the gathering, the hall of Sri Sri Shiv Mandir, the dais, and the long table.",
    play: "Play",
    fig: "Fig.",
  },
  information: {
    eyebrow: "Affiliation",
    title: "Event information",
    lead: "",
    affiliation:
      "Yogasana Bharat, New Delhi, is the national affiliation of the All Bengal Yogasana Sports Association.",
    organisersEyebrow: "Joint organisers",
    organisersTitle: "Joint organisers",
    organisers:
      "Karmyog for the 21st Century and Bharatiya Krishak Samaj are joint organisers of the championship.",
    closeEyebrow: "Close",
    closeTitle: "Prakriti Jagaran Mancha",
    closeName: "Prakriti Jagaran Mancha",
    closePlace: "Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum",
    closeDate: "",
  },
  yogasana: {
    eyebrow: "The sport",
    title: "From practice to performance.",
    em: "",
    lead: "From district competition to the state.",
    practice:
      "Yogasana at this championship began on the mat, as a discipline of repetition, control and precision. Beside the health centre at Muluk, athletes prepared the performance a judging panel later assessed. The association team led that work from the front of the mat.\n\nWhat was practised together in the morning was later performed. The sport is the continuity between those two moments: preparation on the grounds, and performance in the hall.",
    sport:
      "District competition led into this state championship. That is the pathway the association held in view: from the district into a state field of men and women.\n\nThe portrait before the championship banner belongs to that gathering.",
    mottoGloss: "Equanimity is Yoga",
    session: "Judged as a sport.",
    pathway:
      "At the championship, practice became performance. Judges assessed athletes. Artistic Yogasana was contested. Competition was the step between district work and higher Yogasana, and a state result can lead on to the national level.",
    mottoNote: "The line on the Yogasana Bharat seal.",
  },
  organisation: {
    eyebrow: "The association",
    title: "The association that held the championship.",
    lead: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association and an executive committee member of Yogasana Bharat, led the championship. With Papiya Bhattacharya (Roy), General Secretary, the association held selection, judging, accommodation, and the route from district competition toward higher Yogasana.\n\nTheir offices were the institutional centre of the four days. Athletes met that structure as a pathway, and as the practical provision of a stay at the ashram.",
    filmedTitle: "Documenting the proceedings.",
    filmed:
      "The association’s work is visible around the athletes: officials gathered in the courtyard, and the hall filmed while the programme is underway.\n\nThe championship was documented alongside the sporting programme, so conversations and proceedings were kept with the competition on the mat.",
    leadersEyebrow: "Event leadership",
    presidentTerm: "State President",
    president: "Shyamal Ta",
    secretaryTerm: "General Secretary",
    secretary: "Papiya Bhattacharya (Roy)",
    joint:
      "Young athletes need a clear view of the competitive route they are entering, so that practice and competition can lead toward higher-level Yogasana.",
    partnersTitle: "Partners",
    abysaRole: "Presents and runs the state championship: selection, judging, accommodation, and preparation for higher-level competition.",
    nationalRole: "National affiliation of the All Bengal Yogasana Sports Association.",
    worldRole: "The World Yogasana mark is carried on the championship banner with Yogasana Bharat.",
    jointRole: "Joint organisers.",
  },
  prakriti: {
    eyebrow: "Beyond the mat",
    title: "Yogasana, food, and the next generation.",
    bangla: "Prakriti Jagaran Mancha",
    lead: "At this championship, Yogasana is held together with healthier food, better farming, and the lives of the next generation. Prakriti Jagaran Mancha is the name under which that concern sits beside the sport.",
    note: "",
    definition: "",
    contextTitle: "Beside the sport.",
    context:
      "The practice on the mat and the question of how people eat and farm are one concern for future generations. Shyamal Ta, State President of the All Bengal Yogasana Sports Association, speaks to that connection in a conversation recorded at the championship.",
  },
  captions: {
    "athletes-hall": {
      alt: "Young athletes in orange shirts seated on the floor of the hall, listening.",
      caption: "Athletes of the state championship, seated in the hall at Sri Sri Shiv Mandir.",
    },
    "hall-assembly": {
      alt: "A wide view of the hall at Sri Sri Shiv Mandir, with the gathering seated before the dais.",
      caption: "The hall at Sri Sri Shiv Mandir, Bharat Sevashram Sangha.",
    },
    "championship-dais": {
      alt: "The dais beneath the banner of the 7th State Yogasana Sports Championship 2026-27.",
      caption: "7th State Yogasana Sports Championship 2026–27, men and women.",
    },
    address: {
      alt: "A speaker in yellow stands at a microphone beside the long table.",
      caption: "An address from the table in the hall.",
    },
    "dais-speaker": {
      alt: "A speaker with a microphone stands among officials at the championship dais.",
      caption: "The dais, with the championship banner behind.",
    },
    "dance-pair": {
      alt: "Two dancers in red and cream perform in the hall while the audience watches.",
      caption: "Dance in the hall during the gathering.",
    },
    "dance-record": {
      alt: "Dancers mid-movement, with a phone held up to record the performance.",
      caption: "The dance in the hall, recorded from the floor.",
    },
    "dance-turn": {
      alt: "Dancers seen from behind, turning in red blouses and cream skirts.",
      caption: "Dancers turn in the hall.",
    },
    remembrance: {
      alt: "A woman in a yellow saree holds a framed portrait at the ceremonial table.",
      caption: "A framed portrait is brought to the long table during the championship gathering.",
    },
    "ceremony-table": {
      alt: "People gathered at a long table under the sign of Sri Sri Shiv Mandir.",
      caption: "The long table beneath the sign of Sri Sri Shiv Mandir.",
    },
    offering: {
      alt: "A woman in white walks toward the dais as the hall watches.",
      caption: "Approaching the dais in the hall.",
    },
    "young-athletes": {
      alt: "Rows of young athletes in orange sit along the mandir corridor.",
      caption: "Young athletes seated along the mandir corridor.",
    },
    "hall-wide": {
      alt: "The long hall opens onto the grounds, with children seated and cameras in the foreground.",
      caption: "The hall at Sri Sri Shiv Mandir, opening onto the grounds.",
    },
    "from-the-floor": {
      alt: "The gathering stands and sits around the dais, many holding phones.",
      caption: "The gathering around the dais, seen from the floor of the hall.",
    },
    "crossing-dais": {
      alt: "A blurred figure crosses in front of the championship dais.",
      caption: "Movement in front of the championship dais.",
    },
    "field-circle": {
      alt: "A circle seated on the ashram field at Muluk.",
      caption: "Athletes sit together on the field at Muluk.",
    },
    courtyard: {
      alt: "People seated on mats in the courtyard, facing an address.",
      caption: "People seated on mats in the courtyard.",
    },
    "practice-ground": {
      alt: "Practitioners hold a low posture on striped mats beside a small fire offering.",
      caption: "Morning yogasana practice on the mats beside the health centre at Muluk.",
    },
    "practice-warrior": {
      alt: "A wide lunge led on the forecourt, with the group practising on an orange mat.",
      caption: "A wide stance during morning practice on the forecourt.",
    },
    "practice-squat": {
      alt: "The group moves into a deep squat during morning practice.",
      caption: "A deep squat during morning practice on the mats.",
    },
    "practice-open": {
      alt: "Practitioners open the chest, arms extended, during the morning session.",
      caption: "Arms extended during morning practice on the mats.",
    },
    "practice-rise": {
      alt: "The group raises both arms, led by the All Bengal Yogasana Sports Association team.",
      caption: "Arms raised, led by the All Bengal Yogasana Sports Association team.",
    },
    "practice-lead": {
      alt: "An instructor seen from behind leads the group, incense smoke rising from the mats.",
      caption: "The association team leads morning practice at Muluk.",
    },
    "interview-seated": {
      alt: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, being filmed in front of the Prakriti Jagaran banner.",
      caption: "Shyamal Ta, State President, in conversation before the Prakriti Jagaran banner.",
    },
    "interview-camera": {
      alt: "A camera on a tripod set up before the event banner.",
      caption: "Recording equipment set up before the event banner.",
    },
    "film-corridor": {
      alt: "The gathering seated before the 7th State Yogasana Sports Championship banner and the Prakriti Jagaran banner.",
      caption: "The gathering seated before the championship banners.",
    },
    "film-athletes": {
      alt: "Athletes in orange seated in the hall at Sri Sri Shiv Mandir.",
      caption: "Athletes seated in the hall of Sri Sri Shiv Mandir.",
    },
    "film-dais": {
      alt: "The championship dais seen from within the seated gathering.",
      caption: "The championship dais, seen from within the gathering.",
    },
    "film-ceremony": {
      alt: "People gathered at the long table inside Sri Sri Shiv Mandir.",
      caption: "The long table during the championship gathering.",
    },
    "indoor-session": {
      alt: "Young athletes seated in rows during an indoor championship session, with officials behind them.",
      caption: "Young athletes seated together during an indoor session in the hall.",
    },
    "yt-verandah-table": {
      alt: "Officials seated at a long table on the verandah, writing on papers beside laptops.",
      caption: "Officials work through papers at a table on the verandah.",
    },
    "yt-standing-balance": {
      alt: "An athlete in a green, white and orange suit holds a standing balance, one foot drawn up behind the head.",
      caption: "An athlete holds a standing balance during a performance.",
    },
    "hall-crew": {
      alt: "A video camera on a tripod stands beside a sound desk and an open laptop on the hall floor.",
      caption: "Recording equipment set up on the hall floor during the championship.",
    },
    "recognition-stand": {
      alt: "An athlete in an orange shirt holds a medal while officials stand beside her in the hall.",
      caption: "An athlete receives a medal during recognition in the hall.",
    },
    "medal-placed": {
      alt: "A medal is placed over an athlete's head in the hall, while a certificate is held beside him.",
      caption: "A medal is placed as a certificate is held beside the athlete, during recognition in the hall.",
    },
    "certificate-youth": {
      alt: "A young athlete in orange holds a certificate in the hall.",
      caption: "An athlete holds a certificate presented in the hall.",
    },
    "portrait-blue": {
      alt: "An athlete waits with folded hands before the championship banner.",
      caption: "An athlete waits with folded hands before the championship banner.",
    },
    "portrait-yellow": {
      alt: "An athlete faces the camera in front of the championship banner, with a microphone clipped on.",
      caption: "An athlete faces the camera during recordings in front of the championship banner.",
    },
    "portrait-braid": {
      alt: "An athlete stands with folded hands and a microphone before the championship banner.",
      caption: "An athlete stands with folded hands while being recorded before the championship banner.",
    },
    "portrait-navy": {
      alt: "An athlete speaks into a microphone before the championship banner.",
      caption: "An athlete speaks into a microphone before the championship banner.",
    },
    "portrait-jersey": {
      alt: "An athlete is recorded before the championship banner on the morning of 3 October.",
      caption: "An athlete is recorded before the championship banner on the morning of 3 October.",
    },
    "interview-banner": {
      alt: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, sits in conversation before the Prakriti Jagaran banner.",
      caption: "Shyamal Ta, State President, in conversation before the Prakriti Jagaran banner.",
    },
    "interview-sofa": {
      alt: "Two men sit for a filmed conversation in front of the championship banner.",
      caption: "A conversation recorded before the championship banner.",
    },
    "organisers-court": {
      alt: "A group stands in the courtyard in front of the ashram building.",
      caption: "Officials and organisers gathered in the courtyard of the ashram.",
    },
  },
};
