import { informationRows, placeLine } from "./facts";
import type { Copy } from "./types";

export const en: Copy = {
  nav: {
    home: "Introduction",
    event: "Championship",
    yogasana: "Yogasana",
    organisation: "People",
    prakriti: "Prakriti",
    story: "Four days",
    gallery: "Gallery",
    media: "Films",
    information: "About",
    menu: "Menu",
    close: "Close",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    skip: "Skip to content",
    skipIntro: "Skip intro",
  },
  footer: "7th State Yogasana Sports Championship 2026–27 · All Bengal Yogasana Sports Association · Yogasana Bharat, New Delhi · World Yogasana",
  lightbox: { previous: "Previous", next: "Next", close: "Close" },
  home: {
    presents: "Yogasana",
    title: "7th State Yogasana Sports Championship",
    bangla: "",
    championship: "2026–27",
    place: placeLine("en"),
    context: "A record of the state championship, held at Bharat Sevashram Sangha.",
    leadEyebrow: "The championship",
    leadTitle: "A structured competitive pathway.",
    leadEm: "",
    lead: "Athletes move from district competition to this state championship, and on to higher-level competition.",
    ctaProgramme: "Contents",
    ctaVisit: "The four days",
    programmeTitle: "Contents",
    programmeLead: "From the opening of the championship to the organisations that held it.",
    duringTitle: "During the championship",
    insideEyebrow: "Inside",
    insideTitle: "Inside the championship",
    insideLead: "Work at the verandah table, a standing balance, and the recording set up in the hall.",
    watchFilm: "Watch the film",
  },
  event: {
    eyebrow: "The championship",
    title: "A state championship, held in one place.",
    present:
      "The All Bengal Yogasana Sports Association presents the championship at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum. The association is affiliated to Yogasana Bharat, New Delhi, and to World Yogasana.",
    championship:
      "This is the state championship of Yogasana for West Bengal. Athletes come through an organised competitive pathway. The gathering ran from 1 to 4 October 2026.",
    motto: "समत्वं योग उच्यते",
    mottoNote: "The line on the Yogasana Bharat seal.",
    whyEyebrow: "The place",
    whyTitle: "The hall and the grounds.",
    whyEm: "",
    why: "Competition and gathering take place in the hall. Practice also moves onto the grounds of the ashram.",
    recordEyebrow: "Colophon",
    recordTitle: "About the championship",
    dateNote: "",
    rows: informationRows("en"),
    whatTitle: "What it is",
    what: "This was a state-level Yogasana championship. The All Bengal Yogasana Sports Association brought athletes from across West Bengal together for practice, competition and judging.",
    sportLink: "Yogasana, as a sport",
    whoTitle: "Who takes part",
    who: "Hundreds of young athletes, men and women, compete. They arrive through a competitive pathway that runs from district competition to this state championship, and on to higher-level competition.",
    judgedTitle: "How it is judged",
    judged: "A designated judging panel evaluates the athletes.",
    gatheringTitle: "In the hall",
    gathering: "The hall holds the competition and the wider gathering. Dance is part of that same gathering.",
    whereTitle: "Where it happens",
    where: "The championship is held at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum, in the hall of Sri Sri Shiv Mandir (শ্রী শ্রী শিব মন্দির).",
    experienceTitle: "What athletes experience",
    experience: "Athletes stayed, practised and ate together across the four days. Accommodation, meals and athlete facilities were provided. The evening session continued under the lights, and certificates and medals were part of the championship.",
  },
  story: {
    eyebrow: "The grounds",
    title: "The gathering on the field.",
    em: "The gathering on the field.",
    hall: "",
    ground: "The morning programme includes flag hosting, a fire offering and Yogasana practice, before the competition.",
    courtyardTitle: "The offering.",
    courtyard: "A fire offering is held in the courtyard at Muluk.",
    arriveTitle: "A different kind of venue.",
    arrive: "The championship is held in the green grounds of Bharat Sevashram Sangha at Muluk. Young athletes gather along the mandir verandah, in a setting unlike a city sports ground.",
    addressTitle: "",
    address: "",
    danceTitle: "",
    dance: "",
    bannerTitle: "",
    banner: "",
    morningTitle: "Know the path you are entering.",
    morning: "Young athletes are asked to understand the competitive route they are entering, not only the event in front of them.",
    practiceTitle: "Practice, together.",
    practice: "Athletes practise together on the mats. The association team leads the session.",
    nightTitle: "",
    night: "",
    interview: "The conversation connects Yogasana with healthier food, better farming and the lives of the next generation.",
    interviewEyebrow: "A conversation",
    interviewTitle: "Beyond the mat.",
    interviewNote: "Dr (Major) Narayan Bhattacharya",
    daysLabel: "The four days",
    daysLead: "Four days at Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum, in the hall of Sri Sri Shiv Mandir.",
    platesEyebrow: "Plates",
    platesTitle: "The visual record",
    days: [
      {
        id: "day-01",
        number: "01",
        title: "The championship opens",
        opening: "The championship opened at Bharat Sevashram Sangha in Muluk.",
        passages: [
          "Athletes who had come through district competition arrived into the state championship, at Muluk, Bolpur, Birbhum. The hall was Sri Sri Shiv Mandir. In that hall, and on the grounds of the ashram, the sporting programme took shape around Yogasana: practice, competition, and judging.",
        ],
        close: "From that opening, the championship moved into its working rhythm.",
      },
      {
        id: "day-02",
        number: "02",
        title: "Gathering into practice",
        opening: "The second day begins along the verandah of Sri Sri Shiv Mandir.",
        passages: [
          "Young athletes sit along the edge of the mandir, in the grounds of Bharat Sevashram Sangha at Muluk.",
          "The gathering then moves onto the field, where they sit together in a circle.",
          "The rhythm turns to movement. Arms rise together, the association team leading from the front. Practice continues on the mats beside the health centre.",
        ],
        close: "Practice gave the second day its physical shape.",
      },
      {
        id: "day-03",
        number: "03",
        title: "The day unfolds",
        opening: "The third day begins in the courtyard at Muluk.",
        passages: [
          "A speaker addresses the gathering, seated on the mats.",
          "Later in the morning, a fire offering is held in the same courtyard.",
          "As the day moves on, athletes stand for portraits before the championship banner. The hall is filmed, and a conversation is recorded in front of that banner. By evening, young athletes sit together indoors, with officials behind them.",
        ],
        close: "By evening, the day had moved from the courtyard into the hall.",
      },
      {
        id: "day-04",
        number: "04",
        title: "The four-day record",
        opening: "The championship ran through 4 October at the same ashram.",
        passages: [
          "Across these days, athletes practised on the mats and competed before a judging panel. Certificates and medals were presented in the hall. They stayed at Bharat Sevashram Sangha, ate together, and shared the grounds and the hall of Sri Sri Shiv Mandir.",
        ],
        close: "What remains is the record of practice, competition, recognition, and time spent together at Muluk.",
      },
    ],
  },
  gallery: {
    eyebrow: "Photographs",
    title: "Photographs from the championship",
    em: "",
    groups: [
      { id: "day-01", kicker: "1 October 2026", title: "The championship opens", note: "The championship opened at Bharat Sevashram Sangha in Muluk, in the hall of Sri Sri Shiv Mandir." },
      { id: "day-02", kicker: "2 October 2026", title: "Gathering into practice", note: "Young athletes gathered along the mandir verandah and on the field, then practised on the mats." },
      { id: "day-03", kicker: "3 October 2026", title: "The day unfolds", note: "A courtyard address and offering, portraits before the banner, a recorded conversation, and an indoor session." },
      { id: "day-04", kicker: "4 October 2026", title: "The four-day record", note: "The championship ran through 4 October at Bharat Sevashram Sangha." },
      { id: "wider", kicker: "The wider record", title: "Hall, recognition, evening", note: "An address at the table, recognition in the hall, and the evening session." },
    ],
  },
  media: {
    eyebrow: "Films",
    title: "Four films from the championship.",
    em: "",
    play: "Play",
    fig: "Fig.",
  },
  information: {
    eyebrow: "Affiliation",
    title: "Event information",
    lead: "",
    affiliation:
      "Yogasana Bharat, New Delhi, is the national affiliation of the All Bengal Yogasana Sports Association.",
    organisersEyebrow: "Joint organisers",
    organisersTitle: "Joint organisers",
    organisers:
      "Karmyog for the 21st Century and Bharatiya Krishak Samaj are joint organisers of the championship.",
    closeEyebrow: "Close",
    closeTitle: "Prakriti Jagaran Mancha",
    closeName: "Prakriti Jagaran Mancha",
    closePlace: "Bharat Sevashram Sangha, Muluk, Bolpur, Birbhum",
    closeDate: "",
  },
  yogasana: {
    eyebrow: "The sport",
    title: "From practice to performance.",
    em: "",
    lead: "Practice comes first.",
    practice:
      "Yogasana begins with discipline. The athletes seen here are not only demonstrating physical postures. They are preparing for a competitive sport in which practice, control, precision and evaluation come together.",
    sport:
      "The competition begins long before an athlete steps onto the mat. Repetition, control and disciplined practice build the foundation for performance. Athletes move from district competition to this state championship, and on to higher-level competition.",
    mottoGloss: "Equanimity is Yoga",
    session: "A sport, not only a practice.",
    pathway:
      "At the championship, practice becomes performance. Judges evaluate athletes, and competition is the route toward higher-level Yogasana.",
    mottoNote: "The line on the Yogasana Bharat seal.",
  },
  organisation: {
    eyebrow: "The association",
    title: "Building a competitive pathway for Yogasana.",
    lead: "Shyamal Ta, State President of the All Bengal Yogasana Sports Association, leads the championship.",
    filmedTitle: "Organising the competition.",
    filmed:
      "The association presents and runs the championship: selection, judging, accommodation, and preparation for higher-level competition. Athletes, officials and the association team carry the days. The hall is filmed as the programme proceeds.",
    leadersEyebrow: "Event leadership",
    presidentTerm: "State President",
    president: "Shyamal Ta",
    secretaryTerm: "Secretary",
    secretary: "Papiya Bhattacharya (Roy)",
    joint:
      "Young athletes need a clear view of the competitive route they are entering, so that practice and competition can lead toward higher-level Yogasana.",
    partnersTitle: "Partners",
    abysaRole: "Presents and runs the championship.",
    nationalRole: "National affiliation of the All Bengal Yogasana Sports Association.",
    jointRole: "Joint organisers.",
  },
  prakriti: {
    eyebrow: "Beyond the mat",
    title: "A healthier life begins with more than exercise.",
    bangla: "Prakriti Jagaran Mancha",
    lead: "At this championship, Yogasana is also discussed alongside healthier food, better farming and the lives of the next generation.",
    note: "",
    definition: "",
    contextTitle: "What we practise is connected to what we eat.",
    context:
      "Yogasana, healthier food and better farming are held together here as one concern for future generations.",
  },
  captions: {
    "athletes-hall": {
      alt: "Young athletes in orange shirts seated on the floor of the hall, listening.",
      caption: "Athletes of the state championship, seated in the hall at Sri Sri Shiv Mandir.",
    },
    "hall-assembly": {
      alt: "A wide view of the hall at Sri Sri Shiv Mandir, with the gathering seated before the dais.",
      caption: "The hall at Sri Sri Shiv Mandir, Bharat Sevashram Sangha.",
    },
    "championship-dais": {
      alt: "The dais beneath the banner of the 7th State Yogasana Sports Championship 2026-27.",
      caption: "7th State Yogasana Sports Championship 2026–27, men and women.",
    },
    address: {
      alt: "A speaker in yellow stands at a microphone beside the long table.",
      caption: "An address from the table in the hall.",
    },
    "dais-speaker": {
      alt: "A speaker with a microphone stands among officials at the championship dais.",
      caption: "The dais, with the championship banner behind.",
    },
    "dance-pair": {
      alt: "Two dancers in red and cream perform in the hall while the audience watches.",
      caption: "Dance in the hall during the gathering.",
    },
    "dance-record": {
      alt: "Dancers mid-movement, with a phone held up to record the performance.",
      caption: "The dance in the hall, recorded from the floor.",
    },
    "dance-turn": {
      alt: "Dancers seen from behind, turning in red blouses and cream skirts.",
      caption: "Dancers turn in the hall.",
    },
    remembrance: {
      alt: "A woman in a yellow saree holds a framed portrait at the ceremonial table.",
      caption: "A framed portrait brought to the table.",
    },
    "ceremony-table": {
      alt: "People gathered at a long table under the sign of Sri Sri Shiv Mandir.",
      caption: "The long table beneath the sign of Sri Sri Shiv Mandir.",
    },
    offering: {
      alt: "A woman in white walks toward the dais as the hall watches.",
      caption: "Approaching the dais in the hall.",
    },
    "young-athletes": {
      alt: "Rows of young athletes in orange sit along the mandir corridor.",
      caption: "Young athletes seated along the mandir corridor.",
    },
    "hall-wide": {
      alt: "The long hall opens onto the grounds, with children seated and cameras in the foreground.",
      caption: "The hall at Sri Sri Shiv Mandir, opening onto the grounds.",
    },
    "from-the-floor": {
      alt: "The gathering stands and sits around the dais, many holding phones.",
      caption: "The gathering around the dais, seen from the floor of the hall.",
    },
    "crossing-dais": {
      alt: "A blurred figure crosses in front of the championship dais.",
      caption: "A figure crosses in front of the championship dais.",
    },
    "field-circle": {
      alt: "A circle seated on the ashram field at Muluk.",
      caption: "A circle seated on the field at Muluk.",
    },
    courtyard: {
      alt: "People seated on mats in the courtyard, facing an address.",
      caption: "People seated on mats in the courtyard.",
    },
    "practice-ground": {
      alt: "Practitioners hold a low posture on striped mats beside a small fire offering.",
      caption: "Morning yogasana practice on the mats beside the health centre at Muluk.",
    },
    "practice-warrior": {
      alt: "A wide lunge led on the forecourt, with the group practising on an orange mat.",
      caption: "A wide stance during morning practice on the forecourt.",
    },
    "practice-squat": {
      alt: "The group moves into a deep squat during morning practice.",
      caption: "A deep squat during morning practice on the mats.",
    },
    "practice-open": {
      alt: "Practitioners open the chest, arms extended, during the morning session.",
      caption: "Arms extended during morning practice on the mats.",
    },
    "practice-rise": {
      alt: "The group raises both arms, led by the All Bengal Yogasana Sports Association team.",
      caption: "Arms raised, led by the All Bengal Yogasana Sports Association team.",
    },
    "practice-lead": {
      alt: "An instructor seen from behind leads the group, incense smoke rising from the mats.",
      caption: "The association team leads morning practice at Muluk.",
    },
    "interview-seated": {
      alt: "Dr (Major) Narayan Bhattacharya being filmed in front of the Prakriti Jagaran banner.",
      caption: "Dr (Major) Narayan Bhattacharya, filmed before the Prakriti Jagaran banner.",
    },
    "interview-camera": {
      alt: "A camera on a tripod set up before the event banner.",
      caption: "A camera set up before the event banner.",
    },
    "film-corridor": {
      alt: "The gathering seated before the 7th State Yogasana Sports Championship banner and the Prakriti Jagaran banner.",
      caption: "The championship environment: the gathering before the banners.",
    },
    "film-athletes": {
      alt: "Athletes in orange seated in the hall at Sri Sri Shiv Mandir.",
      caption: "Athletes seated in the hall.",
    },
    "film-dais": {
      alt: "The championship dais seen from within the seated gathering.",
      caption: "The championship dais, from within the gathering.",
    },
    "film-ceremony": {
      alt: "People gathered at the long table inside Sri Sri Shiv Mandir.",
      caption: "The wider gathering, at the long table.",
    },
    "indoor-session": {
      alt: "Young athletes seated in rows during an indoor championship session, with officials behind them.",
      caption: "Young athletes seated together during an indoor session in the hall.",
    },
    "yt-verandah-table": {
      alt: "Officials seated at a long table on the verandah, writing on papers beside laptops.",
      caption: "Officials work through papers at a table on the verandah.",
    },
    "yt-standing-balance": {
      alt: "An athlete in a green, white and orange suit holds a standing balance, one foot drawn up behind the head.",
      caption: "An athlete holds a standing balance during a performance.",
    },
    "hall-crew": {
      alt: "A video camera on a tripod stands beside a sound desk and an open laptop on the hall floor.",
      caption: "A camera, sound desk and laptop set up on the floor of the hall.",
    },
    "recognition-stand": {
      alt: "An athlete in an orange shirt holds a medal while officials stand beside her in the hall.",
      caption: "An athlete holds a medal during the recognition in the hall.",
    },
    "medal-placed": {
      alt: "A medal is placed over an athlete's head in the hall, while a certificate is held beside him.",
      caption: "A medal is placed over an athlete's head in the hall.",
    },
    "certificate-youth": {
      alt: "A young athlete in orange holds a certificate in the hall.",
      caption: "A young athlete holds a certificate in the hall.",
    },
  },
};
