export type Locale = "en" | "bn";

export type PlateText = { alt: string; caption: string };

export type Copy = {
  nav: {
    home: string;
    event: string;
    yogasana: string;
    organisation: string;
    prakriti: string;
    story: string;
    gallery: string;
    media: string;
    information: string;
    menu: string;
    close: string;
    language: string;
    english: string;
    bangla: string;
    skip: string;
    skipIntro: string;
  };
  footer: string;
  lightbox: { previous: string; next: string; close: string };
  home: {
    presents: string;
    title: string;
    bangla: string;
    championship: string;
    place: string;
    leadEyebrow: string;
    leadTitle: string;
    leadEm: string;
    lead: string;
    context: string;
    heroAlt: string;
    ctaProgramme: string;
    ctaVisit: string;
    programmeTitle: string;
    programmeLead: string;
    duringTitle: string;
    insideEyebrow: string;
    insideTitle: string;
    insideLead: string;
    watchFilm: string;
  };
  yogasana: {
    eyebrow: string;
    title: string;
    em: string;
    lead: string;
    practice: string;
    sport: string;
    session: string;
    pathway: string;
    mottoNote: string;
    mottoGloss: string;
  };
  organisation: {
    eyebrow: string;
    title: string;
    lead: string;
    filmedTitle: string;
    filmed: string;
    leadersEyebrow: string;
    presidentTerm: string;
    president: string;
    secretaryTerm: string;
    secretary: string;
    joint: string;
    partnersTitle: string;
    abysaRole: string;
    nationalRole: string;
    worldRole: string;
    jointRole: string;
    eventLeadership: string;
    eventLeadershipTitle: string;
    institutionalLeadership: string;
    institutionalLeadershipTitle: string;
    institutionalNote: string;
    profiles: Record<string, { name: string; role: string; detail: string; alt: string }>;
  };
  prakriti: {
    eyebrow: string;
    title: string;
    bangla: string;
    lead: string;
    note: string;
    definition: string;
    contextTitle: string;
    context: string;
  };
  event: {
    eyebrow: string;
    title: string;
    present: string;
    championship: string;
    motto: string;
    mottoNote: string;
    whyEyebrow: string;
    whyTitle: string;
    whyEm: string;
    why: string;
    recordEyebrow: string;
    recordTitle: string;
    dateNote: string;
    rows: { term: string; value: string; lang?: "bn" }[];
    whatTitle: string;
    what: string;
    whoTitle: string;
    who: string;
    judgedTitle: string;
    judged: string;
    gatheringTitle: string;
    gathering: string;
    whereTitle: string;
    where: string;
    experienceTitle: string;
    experience: string;
    sportLink: string;
  };
  story: {
    eyebrow: string;
    title: string;
    em: string;
    hall: string;
    ground: string;
    courtyardTitle: string;
    courtyard: string;
    arriveTitle: string;
    arrive: string;
    addressTitle: string;
    address: string;
    danceTitle: string;
    dance: string;
    bannerTitle: string;
    banner: string;
    morningTitle: string;
    morning: string;
    practiceTitle: string;
    practice: string;
    nightTitle: string;
    night: string;
    interview: string;
    interviewEyebrow: string;
    interviewTitle: string;
    interviewNote: string;
    daysLabel: string;
    daysLead: string;
    platesEyebrow: string;
    platesTitle: string;
    days: { id: string; number: string; title: string; opening: string; passages: string[]; close: string }[];
  };
  gallery: {
    eyebrow: string;
    title: string;
    em: string;
    groups: { id: string; kicker: string; title: string; note: string }[];
  };
  media: {
    eyebrow: string;
    title: string;
    em: string;
    play: string;
    fig: string;
  };
  information: {
    eyebrow: string;
    title: string;
    lead: string;
    affiliation: string;
    organisersEyebrow: string;
    organisersTitle: string;
    organisers: string;
    closeEyebrow: string;
    closeTitle: string;
    closeName: string;
    closePlace: string;
    closeDate: string;
  };
  captions: Record<string, PlateText>;
};
